apiVersion: v1
kind: Service
metadata:
 name: wordpress
 annotations:
  metallb.universe.tf/allow-shared-ip: shared
spec:
 selector:
  app: wordpress
 type: LoadBalancer
 ports:
 - port: 5050
   name: wordpress-http
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: wordpress
spec:
 replicas: 1
 selector:
  matchLabels:
   app: wordpress
 template:
  metadata:
   labels:
    app: wordpress
  spec:
   containers:
   - name: wordpress
     image: image-wordpress
     imagePullPolicy: Never
     livenessProbe:
       httpGet:
         path: /
         port: 5000
         scheme: HTTP
       initialDelaySecond: 5
       periodSeconds: 15
       timeoutSeconds: 5
     readinessProbe:
       httpGet:
         path: /
         port: 5000
         scheme: HTTP
       initialDelaySeconds: 5
       timeoutSeconds: 1
